config/routes.rb
DriveLicence::Application.routes.draw do
  resources :students
  root 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessor :name, :phone
  validates :name, presence: true, length: { maximum: 50 }
  VALID_PHONE_REGEX = /\d{11}/
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }, uniqueness: true
  has_secure_password
  validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :sex, :phone, :course)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    = stylesheet_link_tag "application", media: "all",
                            "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{:charset => "UTF-8"}
  %body
    %header
      .navbar.navbar-inverse.navbar-fixed-top
        .container
          %a.navbar-brand{:href => "/"}
            Differential
          %ul.nav.navbar-nav.pull-right.visible-lg
            %li
              %a{:href => "#"} About
            %li
              %a{:href => "#"} Companies
            %li
              %a{:href => "#"} Team
            %li
              %a{:href => "#"} Blog
            %li
              %a{:href => "#"} Jobs
            %li
              %a{:href => "#"} Contact
          %a.mobile-menu-trigger.pull-right.hidden-lg{:href => "#mobileNav"}
            %i.icon-reorder
          #mobile-menu{:style => "display: none;"}
            %ul
              %li
                %a{:href => "#"} About
              %li
                %a{:href => "#"} Companies
              %li
                %a{:href => "#"} Team
              %li
                %a{:href => "#"} Blog
              %li
                %a{:href => "#"} Jobs
              %li
                %a{:href => "#"} Contact
    .section
      = yield
    %footer>
      .footer-top
        .footer-inner
        .footer-content
          .container
            .row
              .col-md-6.map
                %h3 We work at Cintrifuse.
                #location-map
              .col-md-3.more-menu
                %h3
                  See More
                %ul
                  %li
                    %a{:href=>"http://github.differential.io"} Open Source
                  %li
                    %a{:href=>"#"} Open Source
              .col-md-3.contact-info
                %h2{:itemprop=>"name"} Differential
                %p
                  %span{:itemprop=>"streetAddress"}299 E. Sixth Street
                  %span{:itemprop=>"addressLocality"}Cincinnati
                  %span{:itemprop=>"addressLocality"}Cincinnati
                %ul.social
                  %li
                    %a{:href=>"http://twitter.com/bedifferential", :target=>"_blank"}
                      %i.icon-twitter
                  %li
                    %a{:href=>"http://twitter.com/bedifferential", :target=>"_blank"}
                      %i.icon-twitter
                  %li
                    %a{:href=>"http://twitter.com/bedifferential", :target=>"_blank"}
                      %i.icon-twitter
      .footer-bottom
        .container
          .copyright
            Copyright © 2013&nbsp;Differential
          %ul.footer-nav
            %li
              %a{:href=>"/"} Home
            %li
              %a{:href=>"/"} Contact

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.haml
%section.billboard
  .container
    .row
      .col-md-7
        .intro.animate.fadeIn
          %h1 Build Your Company.
          %p.lead We help entrepreneurs turn great ideas into great companies. We're not an agency or an accelerator. We're a partner.
          %a{:href=>"#"} Learn More
          %i.icon-caret-right
%section.what-we-do
  .container
    .section-title
      %span WHAT WE DO
    .row
      .col-md-4
        %h2 We Build
        %p First and foremost we build things. We put sweat and tears in. We code, we design, we market. We draw interfaces, we fix bugs. We bring raw ideas to life.
      .col-md-4
        %h2 We Mentor
        %p We take equity in our projects, so their success is important to us. We're able to bring decades of startup experience to critical project decisions.
      .col-md-4
        %h2 We Connect
        %p We maintain and share a network of entrepreneurs, marketers, developers, designers, mentors, investors, lawyers and advisors in the startup industry.
      %a{:href=>"#"}See our process
      %i.icon-angle-right
%section.call-to-action
  .container
    .row
      .col-md-6.col1
        %i.icon-thumbs-up
        %p Sign up for early access to the companies and products we build.
      .col-md-6.col2
        %form#mc-embedded-subscribe-form.form-inline.validate.form-inline{:action => "http://differential.us6.list-manage.com/subscribe/post?u=8af2fc04c48538e13aa17fe44&amp;id=172d9c308e", :height => "280px", :method => "post", :name => "mc-embedded-subscribe-form", :target => "_blank"}
          %input#mce-EMAIL.form-control{:name => "EMAIL", :placeholder => "Email Address", :type => "email", :value => ""}
          %button#mc-embedded-subscribe.bttn.bttnBlue.animate.pulse{:name => "subscribe", :type => "submit"} Go

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @student.sex %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>